.idea/misc.xml
src/Day1/Practice/Practice.java

Practice package, practice class edit

---

src/Day1/Practice/Practice.java

first push

---

src/Day4/Java/JavaArithmeticOperators2.java
src/Day4/Practice/BakhriDin.java

Please check my code if no any issues merge it into main and delete the Day_4_Home_Work

Day_4_Home_Work

---

JavaCourse/.idea/workspace.xml
src/Day5/Practice/BakhridinDay_05.java

Please check my code and merge it if everything is correct

Day 5 Home Work

---

src/Day5/Practice/GroupProject.java

There was a conflict with Malika's Day4 code the first time we pushed, but we pulled and pushed again and it seems to be resolved - can a Mentor please review? We don't want to break everything :)

Saturday Group Project - Group 1

---

src/Day5/Practice/Arthur.java

arthurDay5

---

src/Day6/Java/JStrings/JavaStrings.java
src/Day6/Java/JStrings/StringConcat.java
src/Day6/Java/JStrings/StringLength.java
src/Day6/Java/JavaComparisonOperators1.java
src/Day6/Java/JavaComparisonOperators2.java
src/Day6/Java/JavaComparisonOperators3.java
src/Day6/Java/JavaComparisonOperators4.java
src/Day6/Java/JavaComparisonOperators5.java
src/Day6/Java/JavaComparisonOperators6.java
src/Day6/Practice/Furkat.java

Day6 Java Class

---

src/Day6/Practice/AnthonyH.java

See Jira for console ran a check.

Day6 Practice - AnthonyH

---

src/Day6/Practice/Sebahattin.java

Day6 Practice - Sebahattin

---

src/Day6/Practice/Andrea.java

Andrea's Work 8-15-22

---

src/Day6/Practice/Bakhridin_StringMethods.java

Please check my code if everything looks good

Java Day 6 String Method Practice

---

src/Day6/Practice/Dilnoza.java

DilnozaDay6Practice

---

src/Day6/Practice/Mustafa.java

Day6 Practice Mustafa

---

src/Day7/Practice/arthur7day.java

[image](https://user-images.githubusercontent.com/24755994/185257109-4130809e-ea99-48e5-8d99-a0de5afedcf9.png)

arthur day 7 homework

---

src/Day7/Practice/Dilnoza.java

Dilnoza br

---

src/Day7/Practice/Bakhridin_String_Methods.java

Day 7 Home Works

---

src/Day7/Practice/AnthonyH.java

Day7AnthonyH-HW

---

src/Day7/Practice/Sebahattin.java

Day7 Homework Sebahattin

---

src/Day7/Practice/Mustafa.java

HW day7 Mustafa

---

src/Day8/Practice/Bakhridin_StringMethods.java

Day_08 String methods

---

src/Day8/Practice/Anthony.java

Day8 AnthonyH. TASK HW

---

src/Day8/Practice/arthur8Day.java

Arthur day 8

---

src/Day8/Practice/Tohir.java

Day 8.Tohir

---

src/Day8/Practice/Sebahattin.java

Day8 Practice - Sebahattin

---

src/Day9/Practice/Andrea.java

Andrea's Day 9 code

---

src/Day9/Practice/Bakhridin_ScannerClassTasks.java

Hi Furkat, please review my codes.

Day 9 scanner Class Tasks

---

src/Day9/Practice/DilnozaPracticeAndHomework.java

Dilnoza day9 Practice and Homework

---

src/Day9/Practice/Anthony.java

Day9AnthonyH-HW

---

src/Day9/Practice/Sebahattin.java

Day9 Homework Sebahattin

---

src/Day10/Practice/Andrea.java

Andrea's Day 10 code

---

src/Saturday_Project_Bakhridin/Task_01.java
src/Saturday_Project_Bakhridin/Task_02.java
src/Saturday_Project_Bakhridin/Task_03.java
src/Saturday_Project_Bakhridin/Task_04.java
src/Saturday_Project_Bakhridin/Task_05.java
src/Saturday_Project_Bakhridin/Task_06.java
src/Saturday_Project_Bakhridin/Task_07.java
src/Saturday_Project_Bakhridin/Task_08.java
src/Saturday_Project_Bakhridin/Task_09.java
src/Saturday_Project_Bakhridin/Task_10.java
src/Saturday_Project_Bakhridin/Task_11.java
src/Saturday_Project_Bakhridin/Task_12.java
src/Saturday_Project_Bakhridin/Task_13.java
src/Saturday_Project_Bakhridin/Task_14.java

Saturday Project Bakhridin

---

src/Day10/Saturday_Sebahattin/Task_01.java
src/Day10/Saturday_Sebahattin/Task_02.java
src/Day10/Saturday_Sebahattin/Task_03.java
src/Day10/Saturday_Sebahattin/Task_04.java
src/Day10/Saturday_Sebahattin/Task_05.java
src/Day10/Saturday_Sebahattin/Task_06.java
src/Day10/Saturday_Sebahattin/Task_07.java
src/Day10/Saturday_Sebahattin/Task_08.java
src/Day10/Saturday_Sebahattin/Task_09.java
src/Day10/Saturday_Sebahattin/Task_10.java
src/Day10/Saturday_Sebahattin/Task_11.java
src/Day10/Saturday_Sebahattin/Task_12.java
src/Day10/Saturday_Sebahattin/Task_13.java
src/Day10/Saturday_Sebahattin/Task_14.java

Day10 Saturday Homework Sebahattin

---

src/Day10/Practice/Anthony.java
src/Day10/Practice/AnthonyTasks.java

Day10TASKandSaturdayHW-ANTHONYH

---

src/Day10/Practice/MalikaTasks.java
src/Day9/Practice/MalikaHomework.java

Day9 Homework - Malika

---

src/Day10/Practice/ArthurDay10.java

arthurDay10

---

src/Day11/Practice/JavaNestedIfStatement_Bakhridin.java

Java Nested IF Statement

---

src/Day11/Practice/Anthony.java

Day11 AnthonyH -TASKS

---

src/Day11/Practice/ArthurDay11.java

ArthurDay11

---

src/Day11/Practice/Andrea.java

Andrea Day 11 Practice

---

src/Day10/Practice/Saturday_Project_2_Tasks/Malika_SaturdayProject2.java

Saturday Project2 - Malika

---

src/Day11/Practice/Malika.java

Tasks Day11 - Malika

---

src/Day12/Practice/arthur12Day.java

Arthur12Day

---

src/Day12/Practice/Malika.java

Tasks Day12 - Malika

---

src/Day12/Practice/Sebahattin.java

Day 12 Homework Sebahattin

---

src/Day12/Practice/Anthony.java
src/Day12/Practice/AnthonyTASKS.java

Day12AnthonyHTasksandHW

---

src/Day12/Practice/Andrea.java

Andrea's Day 12 Code

---

src/Day13/Practice/Sebahattin.java

Day 13 Homework Sebahattin

---

src/Day13/Practice/Bakhridin_HomeWork.java

Day_13_Home_Work

---

src/Day13/Practice/Andrea.java

Andrea's Day 13 code

---

src/Day13/Practice/MalikaHW.java
src/Day13/Practice/MalikaTasks.java

Malikaday13

---

src/Day12/Practice/MalikaHW.java

Homework Day12 - Malika

---

src/Day13/Practice/Anthony.java
src/Day13/Practice/AnthonyTASKS.java

Day13 Anthony HW and Tasks

---

src/Day13/Practice/Tohir.java

Day 13 assignment

---

src/Day14/Practice/Andrea.java

Andrea's Day 14 Homework

---

src/Day14/Practice/Sebahattin.java

Day14 Homework Sebahattin

---

src/Day14/Practice/Bakhridin_RandomClass_MathRandom.java

Random Classs and Math random method

---

src/Day14/Practice/Mustafa.java

Day 14 Tasks and HW

---

src/Day13/Practice/Mustafa.java

Mustafa Late HW submit day13

---

src/Day14/Practice/arthur14day.java

Arthur14Day

---

src/Day14/Practice/Tohir.java

Tohir day 14 solution

---

src/Day14/Practice/MalikaHw.java

Day14 Homework - Malika

---

src/Day15/Practice/Said.java

while vs. do while 
Using Examples

explanation of difference between while and do while

---

src/Day15/Java/JavaDoWhileLoop.java
src/Day15/Practice/Mustafa.java

Mustafa Task day15

---

src/Day15/Practice/Andrea.java

Andrea's Day 15 practice code

---

src/Day16/Practice/Anthony.java

Day16 Anthony H. -Tasks

---

src/Day16/Practice/Andrea.java

Andrea's Day 16 Practice

---

src/Day16/Practice/Arthur16Day.java

ArthurDay16

---

src/Day16/Practice/Sebahattin.java

Day16 Tasks Sebahattin

---

src/Day15/Practice/Malika.java

Tasks Day15 - Malika

---

src/Day16/Practice/Malika.java

Tasks Day16 - Malika

---

src/Day16/Practice/Bakhridin_ForLoopTasks/Task_01.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_02.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_03.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_04.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_05.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_06.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_07.java
src/Day16/Practice/Bakhridin_ForLoopTasks/Task_08.java

Day 16 Tasks

---

src/Day17/Practice/Anthony.java
src/Day17/Practice/AnthonyTASKS.java

Day17 Anthony HW & TASKS

---

src/Day17/Practice/Sebahattin.java
src/Day17/Practice/SebahattinHomework.java

Day17 homework sebahattin

---

src/Day17/Practice/MalikaTasks.java

Tasks Day17 - Malika

---

src/Day19/Practice/arthur19day.java

arthur19day

---

src/Day18/Practice/Arthur18Day.java

Arthur18Day

---

src/Day19/Practice/Anthony.java

Day19 Anthony Tasks

---

src/Day18/Practice/Anthony.java

Day18 AnthonyH TASKS

---

src/Day19/Practice/Sebahattin.java

Day19 Tasks Sebahattin

---

src/Day18/Practice/Sebahattin.java

Day18 Tasks Sebahattin

---

src/Day19/Practice/Bakhridin/JavaArraysForLoop.java
src/Day19/Practice/Bakhridin/JavaEnhancedForLoop.java

Day19_Bakhridin

---

src/Day18/Practice/Bakhridin_Day_18/JavaArrays.java
src/Day18/Practice/Bakhridin_Day_18/Task1.java
src/Day18/Practice/Bakhridin_Day_18/Task2.java
src/Day18/Practice/Bakhridin_Day_18/Task3.java
src/Day18/Practice/Bakhridin_Day_18/Task4.java

Day_18_Bakhridin

---

src/Day17/Practice/Malika_Hw.java

Day17 Hw - Malika

---

src/Day18/Practice/Malika.java

Day18 Tasks - Malika

---

src/Day18/Practice/Andrea.java

Andrea's Day 18 code

---

src/Day17/Practice/Tohir.java

Tohir day 17

---

src/Day20/Practice/DilnozaTasks/Task2.java
src/Day20/Practice/DilnozaTasks/Task3.java
src/Day20/Practice/DilnozaTasks/Task4.java
src/Day20/Practice/DilnozaTasks/Task5.java
src/Day20/Practice/DilnozaTasks/Task6.java
src/Day20/Practice/DilnozaTasks/Task9.java

Dilnoza group project week4

---

src/Day20/Practice/Sebahattin/Examples.java
src/Day20/Practice/Sebahattin/Task01.java
src/Day20/Practice/Sebahattin/Task02.java
src/Day20/Practice/Sebahattin/Task03.java
src/Day20/Practice/Sebahattin/Task04.java
src/Day20/Practice/Sebahattin/Task05.java
src/Day20/Practice/Sebahattin/Task06.java
src/Day20/Practice/Sebahattin/Task07.java
src/Day20/Practice/Sebahattin/Task08.java
src/Day20/Practice/Sebahattin/Task09.java
src/Day20/Practice/Sebahattin/Task10.java

Sebahattin Day20 Tasks and Homework

---

src/Day20/Practice/AnthonyTASKS.java

Day 20 Anthony TASKS

---

src/GroupTasks/Week4/Task1.java
src/GroupTasks/Week4/Task10.java
src/GroupTasks/Week4/Task2.java
src/GroupTasks/Week4/Task3.java
src/GroupTasks/Week4/Task4.java
src/GroupTasks/Week4/Task5.java
src/GroupTasks/Week4/Task6.java
src/GroupTasks/Week4/Task7.java
src/GroupTasks/Week4/Task8.java
src/GroupTasks/Week4/Task9.java

Group Project Week4 TASKS

---

src/Day20/Practice/Andrea.java

Andrea's Day 20 code

---

src/Day19/Practice/Andrea.java

Andrea's Day 19 code

---

src/Day21/Practice/Arthur21Dayhmwk.java

arthur21day

---

src/Day21/Practice/SebahattinHomework.java

Day 21 Homework Sebahattin

---

src/Day21/Practice/Tohir/Assignment.java
src/Day21/Practice/Tohir/Java_2D_Array.java
src/Day21/Practice/Tohir/Task_1.java
src/Day21/Practice/Tohir/Task_2.java

Tohir Day 21

---

src/Day21/Practice/Andrea.java

Andrea's Day 21 Homework

---

src/Day21/Practice/Dilnoza.java

Dilnoza HomeWork day21

---

src/Day22/Practice/Anthony.java
src/Day22/Practice/AnthonyTask1.java
src/Day22/Practice/AnthonyTask2.java

Day22 Anthony HW and Tasks

---

src/Day22/Practice/Dilnoza.java

Dilnoza Homework

---

src/Day22/Practice/Sebahattin.java

Day 22 Homework Sebahattin

---

src/Day22/Practice/Arhtur22Day.java

arthur22day

---

src/Day22/Practice/Andrea/Day22/HomeworkTask1.java
src/Day22/Practice/Andrea/Day22/HomeworkTask2.java
src/Day22/Practice/Andrea/Day22/HomeworkTask3.java
src/Day22/Practice/Andrea/Day22/HomeworkTask4.java
src/Day22/Practice/Andrea/Day22/Practice.java
src/Day22/Practice/Andrea/Day22/Task1.java
src/Day22/Practice/Andrea/Day22/Task2.java
src/Day22/Practice/Andrea/Day22/Task3.java

Andrea's Day 22 Homework and Practice

---

src/Day22/Practice/Mustafa.java
src/Day23/Practice/Mustafa.java

Tasks day23 by Mustafa

---

src/Day23/Practice/AnthonyTask1.java
src/Day23/Practice/AnthonyTask2.java

Day 23 Anthony Tasks

---

src/Day23/Practice/Dilnoza/Task1.java
src/Day23/Practice/Dilnoza/Task2.java

Dilnoza Day23 Tasks

---

src/Day23/Practice/Day23/Andrea/MethodOverloading.java
src/Day23/Practice/Day23/Andrea/Practice.java
src/Day23/Practice/Day23/Andrea/Task1.java
src/Day23/Practice/Day23/Andrea/Task2.java

Andrea's Day 23 code

---

src/Day24/Practice/ArthurDay24hmk.java

arthur24day

---

src/Day24/Practice/Malika_Tasks/Task3.java
src/Day24/Practice/Malika_Tasks/Tasks_1and2.java

Tasks Day24 - Malika

---

src/Day24/Practice/SaturdayTasksWeek5/Task1.java
src/Day24/Practice/SaturdayTasksWeek5/Task2.java
src/Day24/Practice/SaturdayTasksWeek5/Task3.java
src/Day24/Practice/SaturdayTasksWeek5/Task4.java
src/Day24/Practice/SaturdayTasksWeek5/Task5.java
src/Day24/Practice/SaturdayTasksWeek5/Task6.java
src/Day24/Practice/SaturdayTasksWeek5/Task7.java
src/Day24/Practice/SaturdayTasksWeek5/Task8.java
src/Day24/Practice/SaturdayTasksWeek5/Task9.java

git push --set-upstream origin AndreaSaturdayProject5

Saturday's Group Project

---

src/Day24/Practice/Day24Andrea/Mentoring.java
src/Day24/Practice/Day24Andrea/PracticeJavaVarArgs.java
src/Day24/Practice/Day24Andrea/PracticeVarArgs2.java
src/Day24/Practice/Day24Andrea/Task1.java
src/Day24/Practice/Day24Andrea/Task2.java
src/Day24/Practice/Day24Andrea/Task3.java

Andrea's Day 24 code

---

src/Day25/Practice/Anthony.java

Day 25 Anthony Tasks

---

src/Day25/Practice/Sebahattin.java

Day25 Practice Sebahattin

---

src/Day24/Practice/AnthonyTask1and2.java
src/Day24/Practice/AnthonyTask3.java

Day 24 Anthony Tasks

---

src/Day25/Practice/Bakhridin.java

Day_25_Bakhridin

---

src/Day26/Practice/Day26Prac.java

arthur26day

---

src/Day24/Practice/Sebahattin/OptionalChallengesToTask09.java
src/Day24/Practice/Sebahattin/Task09.java
src/Day26/Practice/Sebahattin.java

I used Turkish characters in the Day24 homework. I just fixed it.

Day26 Practice Sebahattin and to change Day24

---

src/Day25/Practice/Andrea.java

Andrea's random code

---

src/Day26/Practice/Malika.java

Tasks Day26 - Malika

---

src/Day25/Practice/Malika.java

Tasks Day25-Malika

---

src/Day27/Practice/Bakhridin_Task1.java

Bakhridin_Day_27

---

src/Day27/Practice/Arthur27Day.java

arthur27day

---

src/Day27/Practice/Malika.java
src/Malika_Tasks/Malika.java
src/Malika_Tasks/Malika_tasks2.java

Malika day27

---

src/Day26/Practice/Anthony.java
src/Day26/Practice/AnthonyOCAexamples.java

Day 26 Anthony Tasks

---

src/Day27/Practice/AnthonyHW.java

Day 27 Anthony HW

---

src/Day28/Practice/Bahridin_JavaArrayList.java

Bahridin_ArrayList

---

src/Day28/Practice/Andrea/Practice1.java
src/Day28/Practice/Andrea/Practice2.java
src/Day28/Practice/Andrea/Practice3.java

Andrea's Day 28 code

---

src/Day28/Practice/Sebahattin.java

Day28 Practice Sebahattin

---

src/Day29/Practice/Art29DayTsk6.java
src/Day29/Practice/ArtDay29tsk4.java
src/Day29/Practice/ArtDay29tsk5.java
src/Day29/Practice/ArtDay29tsk7.java
src/Day29/Practice/ArtDay29tsk8.java
src/Day29/Practice/ArtDay29tsk9.java
src/Day29/Practice/ArthurDay29Tsk3.java

arthur29daySatHmwk

---

src/Day29/Practice/SaturdayProject6Andrea/Task1.java
src/Day29/Practice/SaturdayProject6Andrea/Task2.java
src/Day29/Practice/SaturdayProject6Andrea/Task3.java
src/Day29/Practice/SaturdayProject6Andrea/Task4.java
src/Day29/Practice/SaturdayProject6Andrea/Task5.java
src/Day29/Practice/SaturdayProject6Andrea/Task6.java
src/Day29/Practice/SaturdayProject6Andrea/Task7.java
src/Day29/Practice/SaturdayProject6Andrea/Task8.java
src/Day29/Practice/SaturdayProject6Andrea/Task9.java

Saturday Project 6 Andrea

---

src/Day29/Practice/Andrea/ArrayList.java
src/Day29/Practice/Andrea/ArrayListContains.java
src/Day29/Practice/Andrea/ArrayListMethods.java
src/Day29/Practice/Andrea/ArrayListMethods2.java
src/Day29/Practice/Andrea/ArrayListMethods3.java
src/Day29/Practice/Andrea/ArrayListRemoveAll.java
src/Day29/Practice/Andrea/ArrayListSet.java
src/Day29/Practice/Andrea/Mentoring.java
src/Day29/Practice/Andrea/RemoveIfMethod.java
src/Day29/Practice/Andrea/Task1.java

Andrea's Day 29 code

---

src/Day27/Practice/Tohir.java

Tohir day 27 homework

---

src/Day28/Practice/AnthonyTask.java

Day 28 Anthony Tasks

---

src/Day29/Practice/Tohir/Task6.java
src/Day29/Practice/Tohir/Task7.java
src/Day29/Practice/Tohir/Task8.java
src/Day29/Practice/Tohir/Task9.java

Tasks 6. 7. 8 and 9 are solved.

Tohir week 7

---

src/Day29/Practice/AnthonyGP6Task1.java
src/Day29/Practice/AnthonyGP6Task2.java
src/Day29/Practice/AnthonyGP6Task3.java
src/Day29/Practice/AnthonyGP6Task4.java
src/Day29/Practice/AnthonyGP6Task5.java
src/Day29/Practice/AnthonyGP6Task6.java
src/Day29/Practice/AnthonyGP6Task7.java
src/Day29/Practice/AnthonyGP6Task8.java
src/Day29/Practice/AnthonyGP6Task9.java
src/Day29/Practice/AnthonyTask.java

Day29 Anthony Task and GP6 Tasks

---

src/Day30/Practice/Malika_Homework.java

Day30 malika

---

src/Day30/Practice/Anthony.java

Day 30 Anthony HW

---

src/Day27/Practice/Malika_Tasks/Malika_tasks2.java

Malika improved errors in her code

---

src/Day30/Practice/Sebahattin.java

Day30 Homework Sebahattin

---

src/Day30/Practice/Bahridin_HomeWork.java

Day_30_Bahridn

---

src/Day30/Practice/Andrea/Homework.java
src/Day30/Practice/Andrea/JavaArrayList.java
src/Day30/Practice/Andrea/Task1.java
src/Day30/Practice/Andrea/Task2.java
src/Day30/Practice/Andrea/Task3.java
src/Day30/Practice/Andrea/UseReturnWithinTheLoop.java

Andrea's Day 30 homework

---

src/Day31/Practice/arthur31hmwk.java

arthur31day

---

src/Day31/Practice/Sebahattin.java

Day31 Homework Sebahattin

---

src/Day31/Practice/Anthony.java

Day 31 Anthony HW

---

src/Day31/Practice/Bahridin_HomeWork.java

bahridin_Day_31

---

src/Day31/Practice/Andrea/Example.java
src/Day31/Practice/Andrea/Homework.java
src/Day31/Practice/Andrea/JavaCollectionMethods.java
src/Day31/Practice/Andrea/JavaSetAddAll.java
src/Day31/Practice/Andrea/JavaSetMethods.java
src/Day31/Practice/Andrea/JavaSets.java
src/Day31/Practice/Andrea/Mentoring.java
src/Day31/Practice/Andrea/Mentoring2.java
src/Day31/Practice/Andrea/Task1.java
src/Day31/Practice/Andrea/Task2.java

Andrea's Day 31 homework and code

---

src/Day32/Practice/arthur32day.java

arthur32day

---

src/Day32/Practice/Bahridin_JavaMapMethods.java

Bahridin_day_32

---

src/Day32/Practice/Anthony.java

Day 32 Anthony Tasks

---

src/Day32/Practice/Andrea/CollectionsWithArrayList.java
src/Day32/Practice/Andrea/JavaForEach.java
src/Day32/Practice/Andrea/JavaMaps.java
src/Day32/Practice/Andrea/JavaTreeSet.java
src/Day32/Practice/Andrea/LinkedHashSetsExample.java
src/Day32/Practice/Andrea/Mentoring.java
src/Day32/Practice/Andrea/Mentoring2.java
src/Day32/Practice/Andrea/Task1.java

git push --set-upstream origin AndreaDay32

Andrea's Day 32 Code

---

src/Day29/Practice/Sebahattin/TAsk03.java
src/Day29/Practice/Sebahattin/Task01.java
src/Day29/Practice/Sebahattin/Task02.java
src/Day29/Practice/Sebahattin/Task04.java
src/Day33/Practice/Sebahattin.java

Day29 Homework and Day33 Task Sebahattin

---

src/Day33/Practice/Bahridin_HomeWork.java

Day_33_Bahridin_HomeWork

---

src/Day33/Practice/Anthony.java

Day 33 Anthony Tasks

---

src/Day33/Practice/Andrea/JavaMapLoops.java
src/Day33/Practice/Andrea/JavaMapLoopsEntrySet.java
src/Day33/Practice/Andrea/Mentoring.java
src/Day33/Practice/Andrea/Mentoring2.java
src/Day33/Practice/Andrea/Mentoring3.java
src/Day33/Practice/Andrea/Task2.java

Andrea's Day 33 code

---

src/Day33/Practice/arthur33prac.java

arthur33day

---

src/Day34/Practice/arthurday34tsk1.java
src/Day34/Practice/arthurday34tsk10.java
src/Day34/Practice/arthurday34tsk2.java
src/Day34/Practice/arthurday34tsk3.java
src/Day34/Practice/arthurday34tsk4.java
src/Day34/Practice/arthurday34tsk5.java
src/Day34/Practice/arthurday34tsk6.java
src/Day34/Practice/arthurday34tsk7.java
src/Day34/Practice/arthurday34tsk8.java
src/Day34/Practice/arthurday34tsk9.java

arthur34homework1-10

---

src/Day34/Practice/Sebahattin_Homework/Task01.java
src/Day34/Practice/Sebahattin_Homework/Task02.java
src/Day34/Practice/Sebahattin_Homework/Task03.java
src/Day34/Practice/Sebahattin_Homework/Task04.java
src/Day34/Practice/Sebahattin_Homework/Task05.java
src/Day34/Practice/Sebahattin_Homework/Task06.java
src/Day34/Practice/Sebahattin_Homework/Task07.java
src/Day34/Practice/Sebahattin_Homework/Task08.java
src/Day34/Practice/Sebahattin_Homework/Task09.java
src/Day34/Practice/Sebahattin_Homework/Task10.java

Day34 Homework Sebahattin

---

src/Day33/Java/JavaMapLoops.java
src/Day34/Practice/SaturdayProject7Andrea/Task1.java
src/Day34/Practice/SaturdayProject7Andrea/Task10.java
src/Day34/Practice/SaturdayProject7Andrea/Task2.java
src/Day34/Practice/SaturdayProject7Andrea/Task3.java
src/Day34/Practice/SaturdayProject7Andrea/Task4.java
src/Day34/Practice/SaturdayProject7Andrea/Task5.java
src/Day34/Practice/SaturdayProject7Andrea/Task6.java
src/Day34/Practice/SaturdayProject7Andrea/Task7.java
src/Day34/Practice/SaturdayProject7Andrea/Task8.java
src/Day34/Practice/SaturdayProject7Andrea/Task9.java

Andrea's Saturday Project Week 7

---

src/Day29/Practice/Ibrahim/Saturday/Task1.java
src/Day29/Practice/Ibrahim/Saturday/Task2.java
src/Day29/Practice/Ibrahim/Saturday/Task3.java
src/Day29/Practice/Ibrahim/Saturday/Task4.java
src/Day29/Practice/Ibrahim/Saturday/Task5.java
src/Day29/Practice/Ibrahim/Saturday/Task6.java
src/Day29/Practice/Ibrahim/Saturday/Task7.java
src/Day29/Practice/Ibrahim/Saturday/Task8.java
src/Day29/Practice/Ibrahim/Saturday/Task9.java
src/Day29/Practice/Ibrahim/Task1.java
src/Day30/Practice/Ibrahim/Task1.java
src/Day30/Practice/Ibrahim/Task2.java
src/Day30/Practice/Ibrahim/Task3.java
src/Day31/Practice/Ibrahim/Homework.java
src/Day31/Practice/Ibrahim/Task1.java
src/Day31/Practice/Ibrahim/Task2.java
src/Day34/Practice/Ibrahim_Saturday/Task1.java
src/Day34/Practice/Ibrahim_Saturday/Task10.java
src/Day34/Practice/Ibrahim_Saturday/Task2.java
src/Day34/Practice/Ibrahim_Saturday/Task3.java
src/Day34/Practice/Ibrahim_Saturday/Task4.java
src/Day34/Practice/Ibrahim_Saturday/Task5.java
src/Day34/Practice/Ibrahim_Saturday/Task6.java
src/Day34/Practice/Ibrahim_Saturday/Task7.java
src/Day34/Practice/Ibrahim_Saturday/Task8.java
src/Day34/Practice/Ibrahim_Saturday/Task9.java

Day 29 Saturday Projects, Day 30, day 31

Ibrahim day 29

---

src/Day34/Practice/Day34Andrea/ExampleForEach.java
src/Day34/Practice/Day34Andrea/JavaMapComputeMethods.java
src/Day34/Practice/Day34Andrea/JavaMapForEachMethod.java
src/Day34/Practice/Day34Andrea/Task1.java

Andrea's Day 34 code

---

src/Day35/Practice/Class_Tasks.java
src/Day35/Practice/Class_Tasks2.java

Class_Tasks

---

src/Day35/Practice/Sebahattin.java

Day35 Task1 Sebahattin

---

src/Day35/Practice/Andrea/MapCodingBat1.java

Andrea's Day 35 code

---

src/Day34/Practice/Anthony/AnthonyTasks.java
src/Day34/Practice/Anthony/GP7/Task1.java
src/Day34/Practice/Anthony/GP7/Task2.java
src/Day34/Practice/Anthony/GP7/Task3.java

Day34 Anthony Tasks & GP7 Tasks

---

src/Day36/Practice/Sebahattin/Examp.java

Day36 Practice Sebahattin

---

src/Day36/Practice/Bahridin_JavaOOP/Task.java

Day_36_JavaOOP

---

src/Day36/Practice/Andrea/Practice.java
src/Day36/Practice/Andrea/School.java
src/Day36/Practice/Andrea/Task.java

Andrea's Day 36 code

---

src/Day37/Practice/Anthony/ConsumerAnthony.java
src/Day37/Practice/Anthony/ProductAnthony.java
src/Day37/Practice/Anthony/Shop.java

Day 37 Anthony Task

---

src/Day37/Practice/Andrea/Day37/Task.java
src/Day37/Practice/Andrea/Day37/Task1/Consumer.java
src/Day37/Practice/Andrea/Day37/Task1/Product.java
src/Day37/Practice/Andrea/Day37/Task1/Shop.java

Andrea's Day 37 code

---

src/Day35/Practice/Day35Task.java
src/Day37/Practice/Art37day.java

arthur37day

---

src/Day38/Practice/arthur38day.java

arthur38day

---

src/Day38/Practice/AnthonyTasks/Consumer.java
src/Day38/Practice/AnthonyTasks/Product.java
src/Day38/Practice/AnthonyTasks/Shop.java
src/Day38/Practice/AnthonyTasks2/Car.java
src/Day38/Practice/AnthonyTasks2/DealerShip.java

Day 38 Anthony Tasks

---

src/Day39/Practice/Anthony/Task1/Rectangle.java
src/Day39/Practice/Anthony/Task1/Shapes.java
src/Day39/Practice/Anthony/Task1/Tasks
src/Day39/Practice/Anthony/Task2/Bank.java
src/Day39/Practice/Anthony/Task2/Branch.java
src/Day39/Practice/Anthony/Task2/City.java

Day 39 Anthony Tasks

---

src/Day39/Practice/Andrea/Constructors/Bank.java
src/Day39/Practice/Andrea/Constructors/Branch.java
src/Day39/Practice/Andrea/Constructors/City.java
src/Day39/Practice/Andrea/Task1/Rectangle.java
src/Day39/Practice/Andrea/Task1/Shapes.java
src/Day39/Practice/Andrea/Task2/Animal.java
src/Day39/Practice/Andrea/Task2/Zoo.java

Andrea's Day 39 code

---

src/Day39/Practice/Arthur39Package/SatTsk.java
src/Day39/Practice/Arthur39Package/Saturday/Customer.java
src/Day39/Practice/Arthur39Package/Saturday/ElectricityAccount.java
src/Day39/Practice/Arthur39Package/Saturday/SaturdayProject
src/Day39/Practice/Arthur39Package/Saturday/Utility.java
src/Day39/Practice/Arthur39Package/Saturday2/Lesson.java
src/Day39/Practice/Arthur39Package/Saturday2/School.java
src/Day39/Practice/Arthur39Package/Saturday2/Student.java
src/Day39/Practice/Arthur39Package/task4.java

arthur39day

---

src/Day39/Practice/Sebahattin/Homework/Task1/Bill.java
src/Day39/Practice/Sebahattin/Homework/Task1/Customer.java
src/Day39/Practice/Sebahattin/Homework/Task1/ElectricityAccount.java
src/Day39/Practice/Sebahattin/Homework/Task1/SaturdayProject
src/Day39/Practice/Sebahattin/Homework/Task2/Lesson.java
src/Day39/Practice/Sebahattin/Homework/Task2/SaturdayProject
src/Day39/Practice/Sebahattin/Homework/Task2/School.java
src/Day39/Practice/Sebahattin/Homework/Task2/Student.java
src/Day39/Practice/Sebahattin/Homework/Task3/SaturdayProject
src/Day39/Practice/Sebahattin/Homework/Task3/Task3.java
src/Day39/Practice/Sebahattin/Practice/Animal/Animal.java
src/Day39/Practice/Sebahattin/Practice/Animal/Tasks
src/Day39/Practice/Sebahattin/Practice/Animal/Zoo.java
src/Day39/Practice/Sebahattin/Practice/BankAndBranch/Bank.java
src/Day39/Practice/Sebahattin/Practice/BankAndBranch/Branch.java
src/Day39/Practice/Sebahattin/Practice/BankAndBranch/City.java
src/Day39/Practice/Sebahattin/Practice/BankAndBranch/Tasks
src/Day39/Practice/Sebahattin/Practice/Shapes/Rectangle.java
src/Day39/Practice/Sebahattin/Practice/Shapes/Shapes.java

Day39 Practice and Homework Sebahattin

---

src/Day39/Practice/Anthony/GroupProject8/SaturdayProject
src/Day39/Practice/Anthony/GroupProject8/Task1/Customer.java
src/Day39/Practice/Anthony/GroupProject8/Task1/ElectricBill.java
src/Day39/Practice/Anthony/GroupProject8/Task1/ElectricityAccount.java
src/Day39/Practice/Anthony/GroupProject8/Task2/Lesson.java
src/Day39/Practice/Anthony/GroupProject8/Task2/School.java
src/Day39/Practice/Anthony/GroupProject8/Task2/Student.java
src/Day39/Practice/Anthony/GroupProject8/Task3/Task3Anthony.java
src/Day39/Practice/Anthony/GroupProject8/Task4/Task4Anthony.java

Anthony GP8 Saturady Tasks

---

src/Day38/Practice/Ibrahim/Task1/Consumer.java
src/Day38/Practice/Ibrahim/Task1/Product.java
src/Day38/Practice/Ibrahim/Task1/Shop.java
src/Day38/Practice/Ibrahim/Task2/Car.java
src/Day38/Practice/Ibrahim/Task2/DealerShip.java
src/Day39/Practice/Ibrahim/Animal/Animal.java
src/Day39/Practice/Ibrahim/Animal/Zoo.java
src/Day39/Practice/Ibrahim/Bank/Bank.java
src/Day39/Practice/Ibrahim/Bank/Branch.java
src/Day39/Practice/Ibrahim/Bank/City.java
src/Day39/Practice/Ibrahim/Saturday/Task1/Bill.java
src/Day39/Practice/Ibrahim/Saturday/Task1/Customer.java
src/Day39/Practice/Ibrahim/Saturday/Task1/ElectricityAccount.java
src/Day39/Practice/Ibrahim/Saturday/Task2/Lesson.java
src/Day39/Practice/Ibrahim/Saturday/Task2/School.java
src/Day39/Practice/Ibrahim/Saturday/Task2/Student.java
src/Day39/Practice/Ibrahim/Saturday/Task3/Task3.java
src/Day39/Practice/Ibrahim/Saturday/Task4/Task4.java

 Ibrahim Day 38, Day 39, Saturday

---

src/Day39/Practice/SaturdayProject8Andrea/Task1/Customer.java
src/Day39/Practice/SaturdayProject8Andrea/Task1/ElectricityAccount.java
src/Day39/Practice/SaturdayProject8Andrea/Task2/Lesson.java
src/Day39/Practice/SaturdayProject8Andrea/Task2/School.java
src/Day39/Practice/SaturdayProject8Andrea/Task2/Student.java
src/Day39/Practice/SaturdayProject8Andrea/Task3/Task3.java
src/Day39/Practice/SaturdayProject8Andrea/Task4/Task4.java

Andrea's unfinished Saturday project

---

src/Day40/Practice/Anthony/OCAexample2/OCA2.java
src/Day40/Practice/Anthony/OCAexample2/OCAfinish.java
src/Day40/Practice/Anthony/Package1/Animals.java
src/Day40/Practice/Anthony/Package1/Birds.java
src/Day40/Practice/Anthony/Package1/JavaAccessModifiers.java
src/Day40/Practice/Anthony/Package2/Shapes.java
src/Day40/Practice/Anthony/Task1/Package1/City.java
src/Day40/Practice/Anthony/Task1/Package1/Country.java
src/Day40/Practice/Anthony/Task1/Package2/World.java
src/Day40/Practice/Anthony/Task1/Package3/Shapes.java
src/Day40/Practice/Anthony/Task1/Package3/taskRectangle.java
src/Day40/Practice/Anthony/Task1/Package4/Shapes.java

Day 40 Anthony H. Tasks

---

src/Day41/Practice/Anthony/ExampleWithFinalAttributes.java
src/Day41/Practice/Anthony/JavaFinalMethods.java
src/Day41/Practice/Anthony/JavaFinalNonAccessModifier.java
src/Day41/Practice/Anthony/JavaStaticAttributes.java
src/Day41/Practice/Anthony/JavaStaticMethods.java
src/Day41/Practice/Anthony/OCA1.java
src/Day41/Practice/Anthony/OCA2.java
src/Day41/Practice/Anthony/Transaction.java

Day 41 Anthony Tasks

---

src/Day41/Practice/Andrea/Mentoring/Task4.java
src/Day41/Practice/Andrea/Practice/JavaFinal.java
src/Day41/Practice/Andrea/Practice/JavaStatic.java
src/Day41/Practice/Andrea/Practice/OCA.java
src/Day41/Practice/Andrea/Practice/OCA2.java

Andrea's Day 41

---

src/Day42/Practice/Sebahattin/Task1/Car.java
src/Day42/Practice/Sebahattin/Task1/Inventory.java
src/Day42/Practice/Sebahattin/Varargs/JavaVarArgs.java

Day42 Practice Sebahattin

---

src/Day42/Practice/Andrea/Mentoring/Task1.java
src/Day42/Practice/Andrea/Practice/JavaVarArgs/JavaVarArgs.java
src/Day42/Practice/Andrea/Practice/Task1/Car.java
src/Day42/Practice/Andrea/Practice/Task1/Inventory.java

Andrea's Day 42 code

---

src/Day36/Practice/Anthony/JavaExamples/Number1/JavaOOP.java
src/Day36/Practice/Anthony/JavaExamples/Number2/OOP2.java
src/Day36/Practice/Anthony/JavaExamples/Number3/OOP3.java
src/Day36/Practice/Anthony/TaskHW/TaskOOP.java
src/Day42/Practice/Anthony/Task1/Car.java
src/Day42/Practice/Anthony/Task1/Inventory.java
src/Day42/Practice/Anthony/Task1/Tasks
src/Day42/Practice/Anthony/VarArgsExamples/Example
src/Day42/Practice/Anthony/VarArgsExamples/JavaVarArgs.java
src/Day42/Practice/Anthony/VarArgsExamples/OCAExampleVarArgs.java

Day42 Tasks and Day36 Tasks and HW Anthony 

---

src/Day34/Practice/Anthony/GP7/Task10.java
src/Day34/Practice/Anthony/GP7/Task4.java
src/Day34/Practice/Anthony/GP7/Task5.java
src/Day34/Practice/Anthony/GP7/Task6.java
src/Day34/Practice/Anthony/GP7/Task7.java
src/Day34/Practice/Anthony/GP7/Task8.java
src/Day34/Practice/Anthony/GP7/Task9.java
src/Day35/Practice/Anthony/Task1.java
src/Day35/Practice/Anthony/Task2.java

Day34 -GP7Tasks Day35-Tasks Anthony

---

src/Day43/Practice/Anthony/OCAHomeworkPractice/Greeting.java
src/Day43/Practice/Anthony/OCAHomeworkPractice/MainTest.java
src/Day43/Practice/Anthony/OCAHomeworkPractice/MyFile.java
src/Day43/Practice/Anthony/OCAHomeworkPractice/X.java
src/Day43/Practice/Anthony/OCAHomeworkPractice/X2.java
src/Day43/Practice/Anthony/OCAinClassHour/OCA1.java
src/Day43/Practice/Anthony/OCAinClassHour/OCA2.java
src/Day43/Practice/Anthony/OCAinClassHour/OCA3/Clothing/Shirt.java
src/Day43/Practice/Anthony/OCAinClassHour/OCA3/OCA3.java
src/Day43/Practice/Anthony/OCAinClassHour/OCA3/Pants/Jeans.java
src/Day43/Practice/Anthony/PracticeTasks/JavaMath.java
src/Day43/Practice/Anthony/PracticeTasks/Name.java
src/Day43/Practice/Anthony/PracticeTasks/Name2.java
src/Day43/Practice/Anthony/PracticeTasks/NameBahodurStyle.java
src/Day43/Practice/Anthony/PracticeTasks/NameInstructor.java
src/Day43/Practice/Anthony/PracticeTasks/Task1

Day 43 Anthony Tasks & Hw

---

src/Day44/Practice/Anthony/Tasks/JavaUnitTest.java
src/Day44/Practice/Anthony/Tasks/OCA2.java
src/Day44/Practice/Anthony/Test/JavaMath.java
src/Day44/Practice/Anthony/Test/experiment.java

Day 44 Anthony Tasks

---

src/Day43/Java/OCAQ66.java
src/Day44/Practice/Andrea/JavaMath.java
src/Day44/Practice/Andrea/Test1.java
src/Day44/SaturdayProject/Andrea/Task1/Employee.java
src/Day44/SaturdayProject/Andrea/Task1/TestSalaries.java
src/Day44/SaturdayProject/Andrea/Task2/Crypto/Bitcoin.java
src/Day44/SaturdayProject/Andrea/Task2/Crypto/Ethereum.java
src/Day44/SaturdayProject/Andrea/Task2/Portfolio/BuyCrypto.java
src/Day44/SaturdayProject/Andrea/Task2/Portfolio/CryptoMarket.java
src/Day44/SaturdayProject/Andrea/Task3/Numbers.java
src/Day44/SaturdayProject/Andrea/Task3/TestNumbers.java
src/Day44/SaturdayProject/Andrea/Task4/PracticeStringVarArgs.java

Andrea's Day 44 code

---

src/Day44/Practice/Sebahattin/JavaUnitTest.java
src/Day44/Practice/Sebahattin/test/JavaMath.java
src/Day44/Practice/Sebahattin/test/Test1.java
src/Day44/SaturdayProject/Sebahattin/Task1/Employee.java
src/Day44/SaturdayProject/Sebahattin/Task1/TestSalaries.java
src/Day44/SaturdayProject/Sebahattin/Task2/Crypto/Bitcoin.java
src/Day44/SaturdayProject/Sebahattin/Task2/Crypto/Ethereum.java
src/Day44/SaturdayProject/Sebahattin/Task2/Portfolio/BuyCrypto.java
src/Day44/SaturdayProject/Sebahattin/Task2/Portfolio/CryptoMarket.java
src/Day44/SaturdayProject/Sebahattin/Task3/Numbers.java
src/Day44/SaturdayProject/Sebahattin/Task3/TestNumbers.java

Day44 Sebahattin Homework and Practice

---

src/Day43/Java/OCAQ66.java
src/Day44/SaturdayProject/SaturdayProjectTasks
src/Day45/Mentoring_10_10/Task1.java
src/Day45/saturdayProject/Task1/Employee.java
src/Day45/saturdayProject/Task1/TestSalaries.java
src/Day45/saturdayProject/Task2/crypto/Bitcoin.java
src/Day45/saturdayProject/Task2/crypto/Ethereum.java
src/Day45/saturdayProject/Task2/cryptoMarket/CryptoMarket.java
src/Day45/saturdayProject/Task2/portfolio/BuyCrypto.java

Saturday Project 
Task1 and Task2

mentoring_10_10

---

src/Day44/SaturdayProject/Andrea/Task2/Crypto/CryptoCurrency.java
src/Day44/SaturdayProject/Andrea/Task2/Portfolio/BuyCrypto.java
src/Day44/SaturdayProject/Andrea/Task2/Portfolio/CryptoMarket.java
src/Day47/Practice/Andrea/Mentoring/Task1.java
src/Day47/Practice/Andrea/Mentoring/Task2.java
src/Day47/Practice/Andrea/Practice/Example/Month.java
src/Day47/Practice/Andrea/Practice/Example/Registration.java
src/Day47/Practice/Andrea/Practice/Example/School.java
src/Day47/Practice/Andrea/Practice/HTTP_STATUS_CODE.java
src/Day47/Practice/Andrea/Practice/JavaEnum.java
src/Day47/Practice/Andrea/Practice/Tasks/BuyProduct.java
src/Day47/Practice/Andrea/Practice/Tasks/Cart.java
src/Day47/Practice/Andrea/Practice/Tasks/Drink.java

Andrea's Day 47 code and amended Task 2 from Saturday Project

---

src/Day44/Practice/Malika/JavaMath.java
src/Day44/Practice/Malika/MathClass.java
src/Day44/Practice/Malika/Test1.java

Day44 - Malika

---

src/Day34/Practice/Malika/Task1.java

Malika - Day34

---

src/Day47/Practice/Tohir_47/HTTP_STATUS_CODES.java
src/Day47/Practice/Tohir_47/JavaEnum.java
src/Day47/Practice/Tohir_47/StudentReg/JavaDuration.java
src/Day47/Practice/Tohir_47/StudentReg/JavaPeriods.java
src/Day47/Practice/Tohir_47/StudentReg/Months.java
src/Day47/Practice/Tohir_47/StudentReg/Registration.java
src/Day47/Practice/Tohir_47/StudentReg/School.java
src/Day47/Practice/Tohir_47/Tasks/BuyProduct.java
src/Day47/Practice/Tohir_47/Tasks/Cart.java
src/Day47/Practice/Tohir_47/Tasks/Drink.java
src/Day48/Practice/Tohir_48/Date/JavaDateTimemanipulation.java
src/Day48/Practice/Tohir_48/Date/JavaLocalDate.java
src/Day48/Practice/Tohir_48/Date/JavaLocalDateTime.java
src/Day48/Practice/Tohir_48/Date/JavaLocalTime.java
src/Day48/Practice/Tohir_48/HW8/CryptoCurrency.java
src/Day49/SaturdayProject/Tohir_Week10/Task2/Application.java
src/Day49/SaturdayProject/Tohir_Week10/Task2/Registration.java
src/Day49/SaturdayProject/Tohir_Week10/Task2/User.java
src/Day49/SaturdayProject/Tohir_Week10/Task3/getLatestDate.java
src/Day49/SaturdayProject/Tohir_Week10/Task4/ConvertDate.java
src/Day49/SaturdayProject/Tohir_Week10/Week10.txt

Day47 and Day48 and Week10 project

Week10Day47Day48

---

src/Day49/SaturdayProject/Andrea/Task1/Product.java
src/Day49/SaturdayProject/Andrea/Task1/Shop.java
src/Day49/SaturdayProject/Andrea/Task1/Task1
src/Day49/SaturdayProject/Andrea/Task1/Transaction.java
src/Day49/SaturdayProject/Andrea/Task1/TransactionType.java
src/Day49/SaturdayProject/Andrea/Task1/test
src/Day49/SaturdayProject/Andrea/Task2/Application.java
src/Day49/SaturdayProject/Andrea/Task2/Registration.java
src/Day49/SaturdayProject/Andrea/Task2/Task2
src/Day49/SaturdayProject/Andrea/Task2/User.java
src/Day49/SaturdayProject/Andrea/Task3/LatestDate.java
src/Day49/SaturdayProject/Andrea/Task3/Task3
src/Day49/SaturdayProject/Andrea/Task4/DateConverter.java
src/Day49/SaturdayProject/Andrea/Task4/Task4

Andrea's Saturday projects

---

src/Day48/Practice/Andrea/Mentoring/HWTask.java
src/Day48/Practice/Andrea/Practice/JavaDate.java
src/Day48/Practice/Andrea/Practice/JavaDateManipulation.java
src/Day48/Practice/Andrea/Practice/JavaPeriods.java
src/Day49/Practice/Andrea/Mentoring/Task1.java
src/Day49/Practice/Andrea/Practice/ComparingDateAndTime.java
src/Day49/Practice/Andrea/Practice/StringToDate.java
src/Day49/Practice/Andrea/Practice/Tasks/Task1.java

Andrea's Day 48 and Day 49 code

---

src/Day50/Practice/Malika.java

Malika - Day50 Tasks 

---

src/Day50/Practice/Andrea/ExceptionExample.java
src/Day50/Practice/Andrea/JavaExceptions.java
src/Day50/Practice/Andrea/OCA122.java

Andrea's Day 50 code

---

src/Day51/Practice/Andrea/Travel.java
src/Day51/Practice/Andrea/Weather.java

Andrea's Day 51 code

---

src/Day51/Practice/arthur51day/Application.java
src/Day51/Practice/arthur51day/Registration.java
src/Day51/Practice/arthur51day/User.java
src/Day51/Practice/arthur51day/task2readme

arthur51day

---

src/Day51/Practice/Malika/Task1.java
src/Day51/Practice/Malika/Travel.java

Malika Day51 Tasks

---

src/Day52/Practice/Andrea/EncapsulationExample.java
src/Day52/Practice/Andrea/Task1/School.java
src/Day52/Practice/Andrea/Task1/SchoolManagement.java
src/Day52/Practice/Andrea/Task1/Student.java
src/Day52/Practice/Andrea/Task2/Application.java
src/Day52/Practice/Andrea/Task2/Cinema.java
src/Day52/Practice/Andrea/Task2/Movie.java
src/Day52/Practice/Andrea/User.java

Andrea's Day 52 code

---

src/Day52/Practice/arthur52daY/Task22/Application.java
src/Day52/Practice/arthur52daY/Task22/Cinema.java
src/Day52/Practice/arthur52daY/Task22/Movie.java

arthur52daY

---

src/Day53/Practice/Andrea/Example/App.java
src/Day53/Practice/Andrea/Example/Apple.java
src/Day53/Practice/Andrea/Example/Banana.java
src/Day53/Practice/Andrea/Example/Fruit.java
src/Day53/Practice/Andrea/Example/Strawberry.java
src/Day53/Practice/Andrea/Inheritance/App.java
src/Day53/Practice/Andrea/Inheritance/SubClass.java
src/Day53/Practice/Andrea/Inheritance/SuperClass.java

Andrea's Day 53 code

---

src/Day54/Practice/Andrea/Mentoring/IntArray.java
src/Day54/Practice/Andrea/Mentoring/JavaStack.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/AccessModifiersInMethodOverride/A.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/AccessModifiersInMethodOverride/B.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/Example1/A.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/Example1/B.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/Example2/C.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/NonAccessModifiersInInheritance/FinalNonAccessModifer/A.java
src/Day54/Practice/Andrea/Practice/AccessModifiers/NonAccessModifiersInInheritance/FinalNonAccessModifer/B.java
src/Day54/Practice/Andrea/Practice/InheritanceInConstructors/A.java
src/Day54/Practice/Andrea/Practice/InheritanceInConstructors/AA.java
src/Day54/Practice/Andrea/Practice/SuperKeyword/A.java
src/Day54/Practice/Andrea/Practice/SuperKeyword/B.java
src/Day54/Practice/Andrea/Practice/SuperKeyword/app.java

Andrea's Day 54 code

---

src/Day54/Practice/AndreaSaturdayProject/Task1/House.java
src/Day54/Practice/AndreaSaturdayProject/Task1/HousePrices.java
src/Day54/Practice/AndreaSaturdayProject/Task1/StatesTax.java
src/Day54/Practice/AndreaSaturdayProject/Task1/Task1
src/Day54/Practice/AndreaSaturdayProject/Task1/TestClass.java
src/Day54/Practice/AndreaSaturdayProject/Task2/App.java
src/Day54/Practice/AndreaSaturdayProject/Task2/Car.java
src/Day54/Practice/AndreaSaturdayProject/Task2/Condition.java
src/Day54/Practice/AndreaSaturdayProject/Task2/Driver.java
src/Day54/Practice/AndreaSaturdayProject/Task2/Task2
src/Day54/Practice/AndreaSaturdayProject/Task2/Vehicle.java
src/Day54/Practice/AndreaSaturdayProject/Task2/Weather.java

Andrea's Saturday Project 11

---

src/Day53/Practice/Malika/Task.java
src/Day53/Practice/Malika/Task1/App.java
src/Day53/Practice/Malika/Task1/Apple.java
src/Day53/Practice/Malika/Task1/Banana.java
src/Day53/Practice/Malika/Task1/Fruit.java
src/Day53/Practice/Malika/Task1/Strawberry.java
src/Day53/Practice/Malika/Task2/Calculate.java
src/Day53/Practice/Malika/Task2/Employee.java
src/Day53/Practice/Malika/Task2/SDET.java

Malika Day53 Tasks

---

src/Day55/Practice/Tohir/Part1/Example1/A.java
src/Day55/Practice/Tohir/Part1/Example1/App.java
src/Day55/Practice/Tohir/Part1/Example1/B.java
src/Day55/Practice/Tohir/Part1/OCA1/A.java
src/Day55/Practice/Tohir/Part1/OCA1/App.java
src/Day55/Practice/Tohir/Part1/OCA1/B.java
src/Day55/Practice/Tohir/Part1/OCA1/C.java
src/Day55/Practice/Tohir/Part1/OCA2/App.java
src/Day55/Practice/Tohir/Part1/StaticandInitializerBlocks/InitializerBlock2.java
src/Day55/Practice/Tohir/Part1/StaticandInitializerBlocks/Person.java
src/Day55/Practice/Tohir/Part1/StaticandInitializerBlocks/StaticBlock.java
src/Day55/Practice/Tohir/Part1/StaticandInitializerBlocks/StaticandNonStatic.java
src/Day55/Practice/Tohir/Part1/Task/Book.java
src/Day55/Practice/Tohir/Part1/Task/Library.java
src/Day55/Practice/Tohir/Part2Abstraction/Example1/A.java
src/Day55/Practice/Tohir/Part2Abstraction/Example1/App.java
src/Day55/Practice/Tohir/Part2Abstraction/Example1/B.java
src/Day55/Practice/Tohir/Part2Abstraction/Example1/C.java
src/Day55/Practice/Tohir/Part2Abstraction/Example2/A.java
src/Day55/Practice/Tohir/Part2Abstraction/Example3/Contractor.java
src/Day55/Practice/Tohir/Part2Abstraction/Example3/Employee.java
src/Day55/Practice/Tohir/Part2Abstraction/Example3/FulltimeEmployee.java
src/Day55/Practice/Tohir/Part2Abstraction/Example3/HR.java

Tohir_Day55

---

src/Day55/Practice/Sebahattin/Task/Book.java
src/Day55/Practice/Sebahattin/Task/Library.java

Sebahattin Day55 Practice

---

src/Day55/Practice/Andrea/Example1/A.java
src/Day55/Practice/Andrea/Example1/App.java
src/Day55/Practice/Andrea/Example1/B.java
src/Day55/Practice/Andrea/ExampleForStaticBlock.java
src/Day55/Practice/Andrea/InitializerBlock.java
src/Day55/Practice/Andrea/Person.java
src/Day55/Practice/Andrea/Task1/Book.java
src/Day55/Practice/Andrea/Task1/Library.java

Andrea's Day 55 code

---

src/Day56/Practice/Sebahattin/Citiy.java
src/Day56/Practice/Sebahattin/Commercial/Commercial.java
src/Day56/Practice/Sebahattin/Commercial/Taxi.java
src/Day56/Practice/Sebahattin/Commercial/Truck.java
src/Day56/Practice/Sebahattin/NonCommercial/NonCommercial.java
src/Day56/Practice/Sebahattin/PublicTransport/PublicTransport.java
src/Day56/Practice/Sebahattin/Vehicle/Vehicle.java

Sebahattin Day56 Practice

---

src/Day57/Practice/Sebahattin/Task/Devices/AbstractDevice.java
src/Day57/Practice/Sebahattin/Task/Devices/Device.java
src/Day57/Practice/Sebahattin/Task/Devices/Model.java
src/Day57/Practice/Sebahattin/Task/Store.java
src/Day57/Practice/Sebahattin/Task/TVs/AbstractTV.java
src/Day57/Practice/Sebahattin/Task/TVs/HdTv.java
src/Day57/Practice/Sebahattin/Task/TVs/SmartTv.java
src/Day57/Practice/Sebahattin/Task/TVs/TVModels.java
src/Day57/Practice/Sebahattin/Task/Tablets/AbstractTablet.java
src/Day57/Practice/Sebahattin/Task/Tablets/Ipad.java
src/Day57/Practice/Sebahattin/Task/Tablets/Samsung.java
src/Day57/Practice/Sebahattin/Task/Tablets/TabletModels.java

Sebahattin Day57 Practice

---

src/Day56/Practice/Andrea/Mentoring/StringBuilderExamples.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/Commercial/Commercial.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/Commercial/Taxi.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/NonCommercial/NonCommercial.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/PublicTransport/Lane.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/PublicTransport/PublicTransport.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/PublicTransport/WorkingShift.java
src/Day56/Practice/Andrea/Practice/ClassVehicle/Vehicle/Vehicle.java

Andrea's Day 56 Code

---

src/Day57/Practice/Andrea/Mentoring/JavaStream.java
src/Day57/Practice/Andrea/Mentoring/StreamFilter.java
src/Day57/Practice/Andrea/Mentoring/StreamMap.java
src/Day57/Practice/Andrea/Practice/AbstractionClass.java
src/Day57/Practice/Andrea/Practice/Interfaces/ElectricCars.java
src/Day57/Practice/Andrea/Practice/Interfaces/GasCars.java
src/Day57/Practice/Andrea/Practice/Interfaces/HybridCars.java
src/Day57/Practice/Andrea/Practice/Task/Devices/AbstractDevice.java
src/Day57/Practice/Andrea/Practice/Task/Devices/Device.java
src/Day57/Practice/Andrea/Practice/Task/Devices/Model.java
src/Day57/Practice/Andrea/Practice/Task/TVs/AbstractTV.java
src/Day57/Practice/Andrea/Practice/Task/TVs/HdTV.java
src/Day57/Practice/Andrea/Practice/Task/TVs/Name.java
src/Day57/Practice/Andrea/Practice/Task/TVs/SmartTV.java
src/Day57/Practice/Andrea/Practice/Task/TVs/TVModels.java
src/Day57/Practice/Andrea/Practice/Task/Tablets/AbstractTablet.java
src/Day57/Practice/Andrea/Practice/Task/Tablets/Samsung.java
src/Day57/Practice/Andrea/Practice/Task/Tablets/TabletModels.java

Andrea's Day 57 code

---

src/UdemySebahattin/EmailApp/Email.java
src/UdemySebahattin/EmailApp/EmailApp.java
src/UdemySebahattin/StudentDatabaseApp/Student.java
src/UdemySebahattin/StudentDatabaseApp/StudentDatabaseApp.java
src/UdemySebahattin/StudentDatabaseApp/Task2

Sebahattin Udemy, task1 and task2

---

src/SaturdayUdemyProject/Andrea/Task1/EmailApp/Department.java
src/SaturdayUdemyProject/Andrea/Task1/EmailApp/Email.java
src/SaturdayUdemyProject/Andrea/Task1/EmailApp/EmailApp.java
src/SaturdayUdemyProject/Andrea/Task2/Course.java
src/SaturdayUdemyProject/Andrea/Task2/RegistrationApp.java
src/SaturdayUdemyProject/Andrea/Task2/Student.java

Andrea's Udemy Project
